AWSTemplateFormatVersion: 2010-09-09

Description: Root Stack for 3 nested Stacks



Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, prod]

  SubnetCidrBlockDEV:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String
    Default: "10.37.32.0/20, 10.37.43.0/24, 10.37.44.0/24, 10.37.34.0/24, 10.37.35.0/24, 10.37.38.0/24, 10.37.39.0/24 "

  SubnetCidrBlockQA:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String
    Default: "10.37.96.0/23, 10.37.96.64/27, 10.37.97.64/27, 10.37.96.32/27, 10.37.97.32/27, 10.37.96.0/27, 10.37.97.0/27 "

  SubnetCidrBlockPROD:
    Description: Comma-delimited list of 6 CIDR blocks
    Type: String
    Default: "10.37.48.0/22, 10.37.48.128/25, 10.37.49.128/25, 10.37.50.0/25, 10.37.50.128/25, 10.37.48.0/25, 10.37.49.0/25 "

Resources:
  RootStackDEV:
    Type: AWS::CloudFormation::Stack
    Properties: 
#      Parameters: 
#        SubnetCidrinformation: !Ref SubnetCidrBlockDEV
      TemplateURL: https://nestedbucket0001.s3.amazonaws.com/ass3devvpc.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: Kartavya.Srivastav@intuitive.cloud


  RootStackQA:
    Type: AWS::CloudFormation::Stack
    Properties: 
#      Parameters: 
#        SubnetCidrinformation: !Ref SubnetCidrBlockQA
      TemplateURL: https://nestedbucket0001.s3.amazonaws.com/ass3vpc.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: Kartavya.Srivastav@intuitive.cloud

  RootStackPROD:
    Type: AWS::CloudFormation::Stack
    Properties: 
#      Parameters: 
#        SubnetCidrinformation: !Ref SubnetCidrBlockPROD
      TemplateURL: https://nestedbucket0001.s3.amazonaws.com/ass3prodvpc.yml
      TimeoutInMinutes: 5
      Tags:
      - Key: Owner
        Value: Kartavya.Srivastav@intuitive.cloud


